# -*- coding: utf-8 -*-
"""Matplotlib_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KWceBWsWm55n8yBUsspWROylm9JD0KH2

**Importing libraries**
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Line and Setp methods**"""

x = np.arange(10)
y1 = [5,6,4,3,2,6,7,3,9,5]
y2 = [1,10,8,3,8,5,2,6,4,10]

lines = plt.plot(x, y1, '--r', x, y2, '-b')

plt.show()

x = np.arange(10)
y1 = [5,6,4,3,2,6,7,3,9,5]
y2 = [1,10,8,3,8,5,2,6,4,10]

lines = plt.plot(x, y1, x, y2)
plt.setp(lines, color='green', linewidth=3) # all lines with same properties

plt.show()