# -*- coding: utf-8 -*-
"""Matplotlib_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_WLEmcsss6kGgQ_j4jQ95lnaYkD7418X

# **Pyplot**
*   It is defined inside matplotlib package,
*   State-based interface,
*   Its functionality is inspired from MATLAB,
*   Mainly intended for interactive plots.

**Importing Library**
"""

# Method 1
import matplotlib.pyplot as plt

# Method 2
from matplotlib import pyplot as plt

data = [1,2,5,6,9]
plt.plot(data)
plt.show()

"""****"""

x_data = [1,2,5,6,7]
y_data = [1,4,25,36,49]

# Formatting plot style '[marker][line][color]'
plt.plot(x_data, y_data, 'o-g', linewidth = 2)
plt.plot(y_data, x_data, 'v--r', linewidth = 2)

# Single line of code
#plt.plot(x_data, y_data, 'o-g', y_data, x_data, 'v--r')

# Adding X and Y labels
plt.xlabel("X Axis")
plt.ylabel("Y Axis")

# Adjusting axis
plt.axis([0,10,0,55]) # axis arguments [xmin, xmax, ymin, ymax]

plt.show()

"""**Importing Numpy Library**"""

import numpy as np

x = np.linspace(0,10,100)
y1 = x**2
y2 = x**2.5
y3 = x**3

# Adding Legends with label
plt.plot(x, y1, ':b', label = "Square", linewidth = 2)
plt.plot(x, y2, '--g', label = "Power 2.5")
plt.plot(x, y3, 'm', label = "Cube")

plt.xlabel("Ranges from 0 to 10")
plt.ylabel("Calculations")

# Adding Title to the plot
plt.title("Three lines on same plot")

plt.legend(loc='center') # Location for Legends
plt.show()

"""**In case of user-defined title**"""

plt.plot(x, y1)
plt.plot(x, y2)
plt.plot(x, y3)

plt.xlabel("Ranges from 0 to 10")
plt.ylabel("Calculations")

add_title = input("Enter title of the plot: ")
plt.title(add_title)

plt.show()