# -*- coding: utf-8 -*-
"""Matplotlib_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hWcsD4exnmSzYLwOVaYt2n58jsl3tpZ7

**Importing libraries**
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Categorical Data Plotting**"""

country = ['USA','India','France','Germany','Brazil']
total_deaths = [1190190,533366,167642,180109,708491] # in millions

plt.bar(country, total_deaths)

plt.xlabel("Name of Countries")
plt.ylabel("Deaths in Millions")

plt.title("COVID-19 Stats")
plt.show()

"""**Applying bar color, edge color and width**"""

country = ['USA','India','France','Germany','Brazil']
total_deaths = [1190190,533366,167642,180109,708491] # in millions

plt.bar(country, total_deaths, color='orange', edgecolor='b', width=0.4)

plt.xlabel("Name of Countries")
plt.ylabel("Deaths in Millions")

plt.title("COVID-19 Stats")
plt.show()

"""**Variations in bar colors**"""

country = ['USA','India','France','Germany','Brazil']
total_deaths = [1190190,533366,167642,180109,708491] # in millions

colors = ['r','b','g','y','c']
plt.bar(country, total_deaths, color=colors, width=0.4)

plt.xlabel("Name of Countries")
plt.ylabel("Deaths in Millions")

plt.title("COVID-19 Stats")
plt.show()