# -*- coding: utf-8 -*-
"""Matplotlib_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EEwgWu1i0Lha_vrxwiTSpbC0yerRhbUo

**Importing libraries**
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Scatter Plot**"""

y1 = np.random.randn(60)
y2 = np.random.randn(60)

plt.scatter(y1,y2)
plt.show()

y1 = np.random.randn(60)
y2 = np.random.randn(60)

plt.scatter(y1,y2)

# Adjusting the axis
plt.axis([-3,3,-3,3])

plt.show()

x = np.arange(60)
y1 = np.random.randn(60)
y2 = np.random.randn(60)

# Specifying a common X axis
plt.scatter(x,y1, marker='^', c='g', label = 'y1 with x')
plt.scatter(x,y2, marker='o', c='r', label = 'y2 with x')

plt.xlabel("X Axis")
plt.ylabel("Y Axis")

plt.title("Scatter Plot")
plt.legend(loc='upper right')
plt.show()